import { createCrepe } from '../src/editor/crepe';
import '../src/styles/tokens.css';
import '../src/styles/app.css';
import '../src/styles/editor.css';

const root = document.getElementById('editor')!;
const result = document.getElementById('result')!;
const sample = '| 名称 | 说明 |\n| --- | --- |\n| 短 | 快 |\n| 长内容 | 这是一段用于检查自动换行的长内容。内容增加时单元格应该自动撑高，不裁切文字，也不会保留多余的段落下边距。 |\n';
let saves = 0;
let created = await createCrepe({root, defaultValue: sample, onMarkdownChange: () => { saves++; }});
result.textContent = '编辑器已就绪';
const { editorViewCtx, parserCtx } = await import('@milkdown/kit/core');
const { undo, redo } = await import('@milkdown/kit/prose/history');
const { TextSelection } = await import('@milkdown/kit/prose/state');
const { addRowAfter, deleteRow } = await import('@milkdown/kit/prose/tables');
const { tableHeightRemark, normalizeRowHeight } = await import('../src/editor/table-height');
const pause = () => new Promise(resolve => setTimeout(resolve, 450)); // 监听器 debounce 200ms，留出余量
const checks: string[] = [];
function check(ok: unknown, message: string) { if (!ok) throw new Error(message); checks.push(message); }
document.getElementById('run')!.onclick = async () => {
  checks.length = 0;
  try {
    const view = created.crepe.editor.action(ctx => ctx.get(editorViewCtx));
    let fired = 0;
    created.crepe.on(l => l.markdownUpdated(() => { fired++; }));
    const initial = view.state.doc;
    const cells = [...root.querySelectorAll('th,td')];
    check(cells.every(cell => getComputedStyle(cell.querySelector('p')!).marginBottom === '0px'), '单元格无额外段落下边距');
    const shortHeight = root.querySelectorAll('tr')[1].getBoundingClientRect().height;
    check(shortHeight < 44, `短行紧凑：${shortHeight.toFixed(1)}px`);
    const pos = 1 + initial.firstChild!.firstChild!.nodeSize;
    view.dispatch(view.state.tr.setNodeAttribute(pos, 'rowHeight', 90));
    await pause();
    check(root.querySelectorAll('tr')[1].getBoundingClientRect().height >= 89, '手动行高应用到 DOM');
    const md = created.crepe.getMarkdown();
    check(md.includes('<!--kv-table-heights:v1 [null,90,null]-->'), '高度保存为表前注释');
    const parsed = created.crepe.editor.action(ctx => ctx.get(parserCtx)(md));
    const parsedRows = parsed.firstChild!;
    check(parsedRows.childCount === 3, '注释解析为行高元数据');
    check(parsedRows.child(0).attrs.rowHeight === null && parsedRows.child(1).attrs.rowHeight === 90 && parsedRows.child(2).attrs.rowHeight === null, '注释高度应用到对应行');
    check(parsed.eq(created.crepe.editor.action(ctx => ctx.get(parserCtx)(created.crepe.getMarkdown()))), 'Markdown 解析序列化稳定往返');
    check(undo(view.state, view.dispatch), '调整支持撤销');
    check(view.state.doc.firstChild!.child(1).attrs.rowHeight === null, '撤销恢复自动行高');
    check(redo(view.state, view.dispatch), '调整支持重做');
    check(view.state.doc.nodeAt(pos)!.attrs.rowHeight === 90, '重做恢复行高');
    view.dispatch(view.state.tr.setSelection(TextSelection.create(view.state.doc, pos + 3)));
    check(addRowAfter(view.state, view.dispatch), '插入行成功');
    check(view.state.doc.firstChild!.child(2).attrs.rowHeight === null, '新行使用自动高度');
    check(view.state.doc.firstChild!.child(1).attrs.rowHeight === 90, '插行保留已有行高');
    view.dispatch(view.state.tr.setSelection(TextSelection.create(view.state.doc, pos + view.state.doc.nodeAt(pos)!.nodeSize + 3)));
    check(deleteRow(view.state, view.dispatch), '删除新行成功');
    check(view.state.doc.firstChild!.child(1).attrs.rowHeight === 90, '删行保留已有行高');
    const html = view.state.schema.nodes.table_row.spec.parseDOM![0];
    const element = document.createElement('tr'); element.style.height = '72px';
    check(typeof html.getAttrs === 'function' && (html.getAttrs(element) as {rowHeight:number}).rowHeight === 72, 'HTML 导入识别行高');
    const nested = '> [!NOTE]\n> <!--kv-table-heights:v1 [null,72]-->\n>\n> | 左 | 右 |\n> | :--- | ---: |\n> | <span style="color:#b23a26">红字</span> | 内容 |\n';
    const nestedDoc = created.crepe.editor.action(ctx => ctx.get(parserCtx)(nested));
    view.dispatch(view.state.tr.replaceWith(0, view.state.doc.content.size, nestedDoc.content));
    const nestedMd = created.crepe.getMarkdown();
    check(nestedMd.includes('kv-table-heights:v1') && nestedMd.includes('color:#b23a26'), 'callout 内高度和行内样式均保留');
    const reparsed = created.crepe.editor.action(ctx => ctx.get(parserCtx)(nestedMd));
    const withoutTrailingParagraph = (doc: typeof view.state.doc) => {
      const json = doc.toJSON() as { content: unknown[] };
      const last = json.content[json.content.length - 1];
      if (JSON.stringify(last) === '{"type":"paragraph"}') json.content.pop();
      return JSON.stringify(json);
    };
    check(withoutTrailingParagraph(reparsed) === withoutTrailingParagraph(view.state.doc), '嵌套表格对齐与内容无损往返（忽略编辑器自动补的空段落）');
    const malformed = {type:'root',children:[{type:'html',value:'<!--kv-table-heights:v1 [null,-2]-->'},{type:'table',children:[{type:'tableRow'},{type:'tableRow'}]}]};
    tableHeightRemark()(malformed);
    check(malformed.children.length === 2 && normalizeRowHeight(Infinity) === null && normalizeRowHeight(1500) === null, '非法高度元数据不应用');
    created.dispose(); await created.crepe.destroy(); root.replaceChildren();
    created = await createCrepe({root, defaultValue: md, onMarkdownChange: () => { saves++; }});
    check(root.querySelectorAll('tr')[1].getBoundingClientRect().height >= 89, '销毁重建后行高保持');
    check(saves > 0, '行高变化触发自动保存回调');
    const restored = created.crepe.editor.action(ctx => ctx.get(editorViewCtx));
    const beforeSaves = saves;
    restored.dispatch(restored.state.tr.setNodeAttribute(pos, 'rowHeight', null));
    check(!created.crepe.getMarkdown().includes('kv-table-heights'), '恢复自动高度后移除元数据');
    await pause();
    check(saves > beforeSaves, `行高变化触发自动保存回调（markdownUpdated 事件数 ${fired}）`);
    const beforeText = saves;
    restored.dispatch(restored.state.tr.insertText('测', pos + 3));
    await pause();
    check(saves > beforeText, '文本编辑触发自动保存回调');
    check(document.querySelectorAll('.table-row-resize').length === 1, '销毁编辑器无残留拖动手柄');
    result.textContent = `PASS ${checks.length} 项\n` + checks.join('\n');
  } catch (error) { result.textContent = `FAIL ${String(error)}\n` + checks.join('\n'); }
};
window.addEventListener('pagehide', () => { created.dispose(); void created.crepe.destroy(); });
setTimeout(() => document.getElementById('run')!.click(), 400);
document.getElementById('run')!.textContent = '重跑回归测试';
